---
resources:
- name: csw-backend
  type: git
  source:
    uri: https://github.com/alphagov/csw-backend.git
    branch: master
- name: csw-configuration
  type: git
  source:
    private_key: |
        ((csw-config-ssh-key))
    uri: git@github.com:alphagov/csw-configuration.git
    branch: concourse

jobs:
- name: job-csw-test-deploy
  serial: true
  plan:
  - get: csw-backend
    trigger: false
  - get: csw-configuration
  - task: terraform-test
    timeout: 30m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: coolteddy/ubuntu18
          tag: latest
      inputs:
      - name: csw-backend
      - name: csw-configuration
      params:
        AWS_REGION: 'eu-west-1'
        ACCOUNT_ID: '103495720024'
        ENVIRONMENT: 'concourse'
        CD_ROLE: 'cd-cybersecurity-tools-concourse-worker'
      run:
        path: sh
        args:
        - -eu
        - -c
        - |
          apt-get update -y

          set -x
          ssh-keygen -m PEM -t RSA -N "" -f /root/.ssh/${ENVIRONMENT}

          cd csw-backend/chalice
          pip install -r requirements-dev.txt

          cd ../build
          npm install

          arn="arn:aws:iam::${ACCOUNT_ID}:role/${CD_ROLE}"

          eval $(aws-assume-role $arn)
          buildcsw 10.11 ${ENVIRONMENT} /root/.ssh/${ENVIRONMENT}.pub
